### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mperez180**
Splash screen has been made responsive, for testing purposes, the top left text denotes the screen size, the one under deonotes the dimensions of the screen at the moment.

### CODE REVIEW

**Comment by hcao-44** [comment]
- Updated the collection of statuses to reflect the ones in the database.
- Updated the ticket status icon in MyTickets screen.
- Added a search bar that allows users to search tickets by title and description in MyTickets screen.
- Fixed the page that displays when a ticket is not found in MyTickets screen.

**Review by nshankaz12 — CHANGES_REQUESTED** [review]
@mperez180 : I can confirm the splash screen is responsive. However, I think this made all the other pages of the app, its contents shifted to the left. Look here for example: 
image. Im thinking its from your changes.

Marie: Create Ticket looks good as of now. I am adding the file attachment feature right now.

Hoai: Everything looks good. Search feature works properly along with the status filters. I also like the "No Tickets" found screen. Nice job!

For now, Im going to request changes from @mperez180 to see if you can find out why all the other screens are being shifted towards the left.

**Review by nshankaz12 — APPROVED** [review]

**Comment by mperez180** [comment]
The screen shift occurred due to disabling, fit to screen. It is needed in order to enable the responsivity of our screens.

**Review by Ghop11 — APPROVED** [review]
lgtm

**Pull request merged**
