### PR TITLE
Created user profile and create ticket page

### PR DESCRIPTION
**Pull request by mkarib**
The user profile page does not have much listed. I can edit this in the future depending on what is needed. The user ticket page is generic so the admin can also use it.

### CODE REVIEW

**Review by Ghop11 — CHANGES_REQUESTED** [review]
The user profile looks good to me. We can think about adding more stuff later. 

We should not allow users to dictate the urgency of their issues. They all think their issue is the highest priority. 

There should be a "title" (subject) field above the description. 

These are the only thing I see on the "Create Ticket Page". Great work!

**Comment by Ghop11** [comment]
@nshankaz12, or I will create a ticket for you in Jira to ensure all the buttons navigate to the correct page. That should be the next thing you are working on. Great work!

**Comment by Ghop11** [comment]
Added "userData" object to APP > OnStart method. This will not interfere will @mkarib PR and can go out whenever this PR is ready. 

userData will contain firstName, lastName, email, and id. 
To use this object on a screen, first, call the object and its key. 

Example: userData.firstName will return the account's first name that is currently logged in.

**Comment by nshankaz12** [comment]
@mkarib, The user profile page looks good for now. We will add more if need to be in the future. The Create Ticket page will be a form field. I will get the exact fields from Brent but that's essentially how that will go. Everything looks good, nice job!

**Review by nshankaz12 — APPROVED** [review]
This looks good to me and its ready to go!

**Review by nshankaz12 — COMMENTED** [review]
@mkarib, The user profile page looks good for now. We will add more if need to be in the future. The Create Ticket page will be a form field. I will get the exact fields from Brent but that's essentially how that will go. Everything looks good, nice job!

**Comment by Ghop11** [comment]
Sounds good! Approving PR.

**Review by Ghop11 — APPROVED** [review]
Lgtm!

**Comment by nshankaz12** [comment]
This is a test for the discord notifications.

**Pull request merged**
