### PR TITLE
Powerapps Redesign

### PR DESCRIPTION
**Pull request by Ghop11**
List of changes I have made. If you made additional changes please leave a comment stating what went in this PR. 

Added components: 
- compMobileHeader
- compWebNav
- compMobileNav

ColorScheme object that holds our colors. 
gbl Nav object

### CODE REVIEW

**Comment by hcao-44** [comment]
Completed the filter menu component
- Add tag filter to menu
- Updated the component with color scheme
- Tag filter only visible for tech and admin
Updated the search function to be able to search with ticket id
Removed redundant code from MyTickets screen

**Comment by hcao-44** [comment]
Update the filter component:
- Removed extra reset icons
- Made adjustments to color scheme of filter menu
Update MyTickets tickets to also pass list of tags to Single ticket info when clicking on a ticket

**Comment by mperez180** [comment]
updated relevant screens, with the new components and color scheme. Screens include: Home, Create a Ticket, My Tickets, Log of All Tickets, and Assign Role.

**Comment by hcao-44** [comment]
Completed redesign of search bar as a component:
- Made the search bar collapse into icon in mobile view
- - Created a search blocker that exists outside of the component to close search bar when in mobile view
- Fixed issue where clicking outside of search bar causes whatever is in search bar to get searched

**Comment by mperez180** [comment]
Single Ticket Info Screen updated

**Review by mperez180 — APPROVED** [review]
Need to close this PR

**Pull request merged**
